Repository CampingOn/CampingOn-FE, pull requests merged in 2024-12, with the labels that each got.

#29 feat : #14 캠핑장 카드 구현
  src/components/CampingCard.js
Labels: feature

#31 Fix: #30 토큰 재발급 api가 여러번 호출되는 문제 해결
  src/App.js
Labels: bug fix

#32 Feat/#16 페이지 확장 버튼, 페이지 상단으로 올라가는 버튼, api 서비스 모듈 작성
  package-lock.json
  package.json
  src/api/services/bookmarkService.js
  src/api/services/campService.js
  src/components/LoadMoreButton.js
  src/components/ScrollToTopFab.js
  src/router/Router.js
Labels: feature, subtask

#34 refactor: 2주차 피드백 반영 및 axios 삭제
  src/App.js
  src/api/axios.js
  src/api/axiosConfig.js
  src/api/services/bookmarkService.js
  src/api/services/campService.js
  src/api/services/reservationService.js
  src/pages/account/Login.js
  src/pages/account/SignUp.js
  src/utils/Auth.js
  src/utils/HiddenUtils.js
Labels: enhancement

#35 refactor: 컴포넌트 import 절대경로로 수정
  src/api/services/bookmarkService.js
  src/api/services/campService.js
  src/api/services/reservationService.js
  src/pages/reservation/ReservationList.js
  src/router/Router.js
Labels: enhancement

#39 Feat/#33 메인페이지 인기캠핑장 불러오기
  src/components/CampingCard.js
  src/pages/home/Home.js
Labels: feature

#41 Feat: #18 Mypage 생성
  public/profile.png
  src/api/services/userService.js
  src/components/InputField.js
  src/components/ProfileCard.js
  src/components/ReservationCard.js
  src/pages/account/DeleteAccount.js
  src/pages/account/MyKeyword.js
  src/pages/account/MyPage.js
  src/pages/account/ProfileView.js
  src/pages/account/UpdateProfile.js
  src/router/Router.js
Labels: feature

#42 feat : #40 추천 캠핑장 목록 조회
  src/pages/home/Home.js
Labels: feature

#46 Feat/#15 main 헤더 컴포넌트 완료
  public/logo.svg
  public/logo192.png
  public/logo512.png
  public/logoClicked.svg
  public/logoWide.svg
  public/logoWideClicked.svg
  src/App.js
  src/components/Header.js
  src/components/WhiteButton.js
  src/components/YellowButton.js
  src/router/Router.js
Labels: feature

#49 Fix/#45 main 헤더 로그인 유무로 변경되나 뭔가 버그가 있음
  src/App.js
  src/api/handlers/errorHandler.js
  src/api/services/reservationService.js
  src/components/Header.js
  src/components/YellowButton.js
  src/components/index.js
  src/context/AuthContext.js
  src/pages/home/Keyword.js
  src/pages/index.js
  src/pages/reservation/ReservationList.js
  src/router/Router.js
Labels: bug, feature

#52 Feat/#51 캠핑장 상세 페이지 작성
  src/components/CampingCard.js
  src/pages/camp/CampDetail.js
  src/pages/home/Home.js
  src/router/Router.js
  src/style/camp-detail.css
Labels: feature

#53 Feat/#10 캠핑장 검색 결과 페이지
  src/api/services/bookmarkService.js
  src/api/services/campService.js
  src/api/services/searchInfoService.js
  src/components/SearchBar.js
  src/pages/index.js
  src/pages/search/Search.js
  src/router/Router.js
Labels: feature

#54 Feat: 캠핑장 관련 카드 생성
  public/default/개인자동차.png
  public/default/글램핑.png
  public/default/오토.png
  public/default/일반.png
  public/default/카라반.png
  src/components/CampBookmarkedCard.js
  src/components/CampReservationCard.js
  src/components/CampSiteCard.js
Labels: feature

#57 Feat/#56 홈페이지 회원, 비회원 구분해서 보여주기
  src/api/services/reviewService.js
  src/components/CampingCard.js
  src/components/ReviewCard.js
Labels: feature

#61 Revert "Feat/#56 홈페이지 회원, 비회원 구분해서 보여주기"
  src/api/services/reviewService.js
  src/components/CampingCard.js
  src/components/ReviewCard.js
Labels: feature

#62 [CONFLICT] : 캠핑카드 충돌 문제 해결
  src/components/CampingCard.js
  src/pages/home/Home.js
Labels: bug fix

#63 refactor : #51 BE 코드 변경으로 인한 변수변경
  src/pages/home/Home.js
Labels: feature

#65 Fix: axiosConfig에 refresh 갱신 대기열
  src/api/axiosConfig.js
Labels: bug fix

#67 Fix: 대기열에서 Loading 뜨는 문제 해결
  src/api/axiosConfig.js
  src/components/ProfileCard.js
  src/pages/account/MyKeyword.js
  src/pages/account/MyPage.js
  src/pages/account/ProfileView.js
Labels: enhancement, bug fix

#70 Feat/#68 찜클릭시 DB 저장
  src/components/CampingCard.js
  src/pages/home/Home.js
  src/pages/search/Search.js
Labels: feature

#73 Feat: #55 구글 로그인 버튼 추가
  public/google-logo.png
  src/api/axiosConfig.js
  src/api/services/userService.js
  src/pages/account/Login.js
  src/pages/account/OAuthSuccess.js
  src/pages/account/SignUp.js
  src/pages/account/UpdateProfile.js
  src/router/Router.js
  src/utils/Validation.js
Labels: feature

#79 Feat/#74 메인페이지, 무한스크롤 상단버튼 추가
  src/pages/home/Home.js
Labels: feature

#80 Feat/#77 .env 파일 삭제
  .env
  .gitignore
Labels: subtask

#85 Feat/#84 .env 파일 재작성, KakoMap.js 추가
  .env
  .gitignore
  public/index.html
  src/components/KakaoMap.js
  src/components/OperationPolicy.js
  src/pages/camp/CampDetail.js
  src/style/camp-detail.css
  src/style/operation-policy.css
Labels: enhancement, feature

#87 Feat/#69 reservation 예약 페이지 대충 완료
  .env
  src/api/services/campSiteService.js
  src/components/ReservationConfirmCard.js
  src/components/YellowButton.js
  src/components/index.js
  src/pages/index.js
  src/pages/reservation/MyReservation.js
  src/pages/reservation/Reservation.js
  src/router/Router.js
Labels: feature

#90 Feat/#89 .env 파일 푸시 제외
  src/components/KakaoMap.js
  src/pages/camp/CampDetail.js
Labels: enhancement

#92 Fix/#91 메인페이지에서 검색 시 검색결과 페이지 반영x
  src/api/services/reviewService.js
  src/api/services/searchInfoService.js
  src/components/ImageUploader.js
  src/components/SearchBar.js
  src/pages/review/CreateReview.js
  src/pages/search/Search.js
Labels: bug

#93 Fix/#50 auth 헤더 버그 해결, 인터셉터 로그포맷 수정, 로고 바리에이션
  src/api/axiosConfig.js
  src/api/services/userService.js
  src/components/Header.js
  src/components/index.js
  src/context/AuthContext.js
  src/pages/account/Login.js
  src/pages/account/SignUp.js
Labels: bug fix

#95 Feat/#74 캠핑장카드 수정, 무한스크롤 intersection Observer 구현
  src/pages/home/Home.js
  src/pages/search/Search.js
Labels: feature

#98 Fix/#97 oauth 구글 유저 로그인상태 갱신
  src/api/axiosConfig.js
  src/context/AuthContext.js
  src/pages/account/OAuthSuccess.js
  src/pages/index.js
  src/router/Router.js
Labels: bug fix

#104 Feat/#86 찜 목록 페이지
  src/api/services/campService.js
  src/components/CampBookmarkedCard.js
  src/components/Header.js
  src/pages/account/MyBookmark.js
  src/router/Router.js
Labels: feature

#106 Feat/#69 reservation 서비스 모듈 수정
  src/api/services/reservationService.js
  src/components/Header.js
Labels: bug fix

#105 Feat: #96 나의 예약 확인 페이지 구현
  package-lock.json
  package.json
  src/api/services/reservationService.js
  src/components/CampReservationCard.js
  src/components/ReservationCard.js
  src/components/index.js
  src/pages/account/ProfileView.js
  src/pages/reservation/MyReservation.js
Labels: feature

#107 Feat/#86 찜목록 페이지 구현 완료
  src/components/CampBookmarkedCard.js
  src/components/CampingCard.js
  src/pages/account/MyBookmark.js
  src/pages/index.js
  src/router/Router.js
Labels: feature

#110 [FIX] #109 사용자 맞춤형 캠핑장 목록 조회 엔드포인트 변경 적용
  public/default/review-image.jpg
  src/api/services/campService.js
  src/api/services/reviewService.js
  src/api/services/searchInfoService.js
  src/components/ImageCarousel.js
  src/components/Review/ReviewForm.js
  src/components/Review/ReviewModal.js
  src/components/index.js
  src/pages/home/Home.js
  src/pages/review/CreateReview.js
  src/router/Router.js
Labels: bug

#113 Feat: #111 키워드 관련 화면 개발
  src/api/services/userService.js
  src/components/KeywordSelection.js
  src/pages/account/Login.js
  src/pages/account/MyKeyword.js
  src/pages/home/Keyword.js
  src/router/Router.js
Labels: feature

#114 Feat/#69 reservation 예약확인 페이지 구현완료
  public/index.html
  public/logo/logo.svg
  public/logo/logoClicked.svg
  public/logo/logoWide.svg
  public/logo/logoWideClicked.svg
  src/App.js
  src/api/services/campSiteService.js
  src/components/CustomSnackbar.js
  src/components/OperationPolicy.js
  src/components/ReservationConfirmCard.js
  src/components/YellowButton.js
  src/components/index.js
  src/pages/account/Login.js
  src/pages/account/SignUp.js
  src/pages/home/Header.js
  src/pages/reservation/Reservation.js
  src/style/operation-policy.css
Labels: feature

#117 Feat/#115 캘린더와 연동되는 예약 가능한 캠핑지 리스트 추가
  src/components/OperationPolicy.js
  src/components/camp/AddressInfo.js
  src/components/camp/AvailableCampSiteList.js
  src/components/camp/AvailableCampSites.js
  src/components/camp/CampDatePicker.js
  src/components/camp/CampDetailIntro.js
  src/components/camp/CampSiteCard.js
  src/components/camp/ImageGallery.js
  src/components/camp/MapSection.js
  src/components/camp/ModalComponent.js
  src/components/camp/ModalGallery.js
  src/components/index.js
  src/hooks/useAvailableCampSites.js
  src/hooks/useCampDetail.js
  src/pages/camp/CampDetail.js
  src/style/available-list.css
  src/style/camp-date-picker.css
  src/style/camp-detail.css
  src/style/modal-component.css
Labels: enhancement, feature

#123 Fix/#121 캘린더 기능 수정
  src/components/camp/CampDatePicker.js
Labels: enhancement

#126 Refactor/#116 reservation 예약날짜 예외처리
  src/components/CampReservationCard.js
  src/components/OperationPolicy.js
  src/components/ReservationConfirmCard.js
  src/pages/reservation/Reservation.js
  src/style/operation-policy.css
Labels: enhancement

#127 Feat/#124 홈페이지 css 수정
  src/components/CampingCard.js
  src/components/MainCarousel.js
  src/pages/home/Home.js
  src/pages/search/Search.js
Labels: feature

#130 Fix/#118 스낵바 수정
  src/components/CampBookmarkedCard.js
  src/components/CampingCard.js
  src/pages/account/MyBookmark.js
  src/pages/home/Home.js
  src/pages/search/Search.js
Labels: bug fix

#132 Fix/#101 header 로그인상태 최종 렌더링만 로그에 출력
  src/components/ReservationConfirmCard.js
  src/pages/home/Header.js
  src/pages/reservation/Reservation.js
Labels: enhancement, bug fix

#141 fix: #140 로고,이미지 엑박 해결. 이미지 경로 수정
  public/favicon.ico
  public/index.html
  src/pages/account/Login.js
  src/pages/account/ProfileView.js
Labels: bug fix

#142 Feat/#131 리뷰 작성, 조회 페이지
  src/api/services/reviewService.js
  src/components/Review/ImageUploader.js
  src/components/Review/ReviewForm.js
  src/components/Review/ReviewModal.js
  src/components/common/ImageCarousel.js
  src/components/reservation/CampReservationCard.js
  src/pages/reservation/MyReservation.js
Labels: feature

#146 Fix/#133 검색 페이지에서 검색 시 파라미터 값을 전해주지 못하는 문제
  src/components/index.js
  src/components/main/NoResultsFound.js
  src/pages/search/Search.js
Labels: bug fix

#147 Style/#94 StyleSelect 컴포넌트 생성 후 적용
  public/favicon.ico
  src/components/common/StyledSelect.js
  src/components/common/YellowButton.js
  src/pages/reservation/Reservation.js
Labels: bug fix

#148 Fix/#100 FE에서 무한 요청되는 문제
  src/api/axiosConfig.js
  src/router/ProtectedRoute.js
  src/router/Router.js
Labels: bug fix

#152 fix: #151 나의예약목록에 디폴트 이미지 못 불러오는 버그 해결
  src/components/reservation/CampReservationCard.js
  src/pages/camp/CampDetail.js
Labels: bug fix

#153 Fix/#143 리뷰 작성된 캠핑장 추천 정보 누락 + 유효성 검사
  src/api/services/reviewService.js
  src/components/Review/ReviewForm.js
  src/components/Review/ReviewModal.js
  src/components/reservation/CampReservationCard.js
Labels: subtask, bug fix

#154 feat : #149 라인 인트로 디폴트 데이터 추가, 해쉬태그 2줄 추가
  src/components/camp/CampingCard.js
  src/pages/home/Home.js
  src/pages/search/Search.js
Labels: enhancement

#156 Fix/#155 캘린더 새로고침 해결, 반려동물 반입 추가
  src/components/camp/CampDatePicker.js
  src/components/common/OperationPolicy.js
  src/pages/camp/CampDetail.js
  src/style/camp-date-picker.css
  src/style/camp-detail.css
Labels: enhancement, feature

#164 Refactor/#161 reservation 썸네일 디폴트이미지 세팅하는 함수 수정
  src/App.js
  src/components/camp/CampBookmarkedCard.js
  src/components/camp/CampSiteCard.js
  src/components/camp/CampingCard.js
  src/components/common/OperationPolicy.js
  src/components/common/YellowButton.js
  src/components/main/SearchBar.js
  src/components/reservation/CampReservationCard.js
  src/pages/camp/CampDetail.js
  src/utils/ThumbnailUtils.js
Labels: enhancement

#167 fix: #166 디폴트 썸네일이미지 안불러와짐 해결
  src/components/reservation/CampReservationCard.js
Labels: bug fix

#169 feat: 자동완성 기능 검색창 구현
  src/api/services/searchInfoService.js
  src/components/main/SearchBar.js
Labels: feature

#170 Feat/#157 상세페이지 campInfo 추가
  src/components/camp/CampInfo.js
  src/pages/camp/CampDetail.js
Labels: feature

#173 refactor: 체크인체크아웃 데이터 프롭 속성명 수정
  src/components/reservation/CampReservationCard.js
Labels: enhancement

#177 Fix/#176 캠핑장 상세 페이지에 리뷰 리스트 추가
  src/api/services/reviewService.js
  src/components/Review/ReviewList.js
  src/components/camp/AddressInfo.js
  src/components/camp/CampDatePicker.js
  src/components/common/OperationPolicy.js
  src/pages/camp/CampDetail.js
  src/pages/review/ReviewDetail.js
  src/router/Router.js
  src/style/available-list.css
  src/style/camp-date-picker.css
  src/style/camp-detail.css
Labels: enhancement, feature

#165 Style: #160 프론트엔드 오피스아워 피드백 반영
  src/api/axiosConfig.js
  src/components/camp/CampBookmarkedCard.js
  src/components/common/CustomInputField.js
  src/components/common/InputField.js
  src/components/index.js
  src/components/reservation/CampReservationCard.js
  src/pages/account/DeleteAccount.js
  src/pages/account/Login.js
  src/pages/account/ProfileView.js
  src/pages/account/SignUp.js
  src/pages/account/UpdateProfile.js
  src/pages/reservation/MyReservation.js
  src/utils/Validation.js
Labels: enhancement, feature

#179 feat : mt-2 로 변경
  src/components/camp/CampingCard.js
Labels: feature

#180 Fix/#178 운영 정책, 카카오 맵 크기 수정
  src/components/Review/ReviewList.js
  src/components/camp/KakaoMap.js
  src/components/common/OperationPolicy.js
  src/pages/camp/CampDetail.js
Labels: enhancement

#183 Fix/#182 리뷰 상세 페이지에 캠핑장 이름 추가, 기능 개선
  src/api/services/reviewService.js
  src/components/Review/ReviewList.js
  src/components/camp/KakaoMap.js
  src/components/common/OperationPolicy.js
  src/pages/camp/CampDetail.js
  src/pages/review/ReviewDetail.js
  src/style/camp-date-picker.css
  src/style/camp-detail.css
Labels: enhancement, feature

#187 style: 검색페이지, 카드 여백 수정
  src/pages/home/Home.js
  src/pages/search/Search.js
Labels: enhancement

#190 Style: #188 캠핑장 상세 페이지 일부 수정
  src/components/Review/ReviewList.js
  src/components/camp/AddressInfo.js
  src/components/camp/CampInfo.js
  src/pages/camp/CampDetail.js
  src/style/camp-detail.css
Labels: enhancement

#194 Fix/#193 스마트폰 지도 URL 접속 문제
  src/components/camp/KakaoMap.js
Labels: enhancement

#197 Refactor/196 style 스낵바 통일, 회원가입시 로그인창으로 바로이동
  public/index.html
  src/components/common/CustomInputField.js
  src/components/common/CustomSnackbar.js
  src/components/common/YellowButton.js
  src/pages/account/MyBookmark.js
  src/pages/account/SignUp.js
  src/pages/home/Home.js
  src/pages/reservation/MyReservation.js
  src/pages/reservation/Reservation.js
  src/pages/search/Search.js
Labels: enhancement

#198 style: snackbar 통일
  src/components/main/KeywordSelection.js
  src/pages/home/Home.js
Labels: enhancement
